name: Gold Premium AI Bot

on:
  schedule:
    # 1. 평일 한국 시간 오전 8시 (KST) 실행 
    - cron: '0 23 * * 1-5'
    
    # 2. 평일 한국 시간 오후 4시 30분 (KST) 실행
    - cron: '30 7 * * 1-5'
    
  # 수동 실행을 위한 워크플로우 디스패치
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          # 1. requirements.txt를 사용하여 필요한 모든 라이브러리 설치
          pip install -r requirements.txt
          
          # 2. matplotlib 설정 디렉터리 안전하게 생성
          mkdir -p ~/.config/matplotlib/
          
          # 3. 그래프 생성을 위한 백엔드 설정 파일 생성
          echo "backend: agg" > ~/.config/matplotlib/matplotlibrc

      - name: Run Gold Premium Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python gold_premium_bot.py
