name: Gold Premium AI Bot

on:
  schedule:
    - cron: "0 23 * * 1-5"  # UTC 23시 = 한국시간 오전 8시 (월~금)
    - cron: "5 14 * * *"  # UTC 11시 = 한국시간 오후 8시 (월~금)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # main 브랜치에서만 실행되도록 제한 (권장)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        # requirements.txt를 사용한다고 가정하고 수정
        run: pip install requests beautifulsoup4 matplotlib openai
        # run: pip install -r requirements.txt 

      - name: Run Gold Premium Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python gold_premium_bot.py
